#pragma once

#include "com_defines.h"
#include "com_types.h"
#include "com_maths.h"
#include "com_transform.h"
#include "com_memory_utils.h"
#include "com_render_types.h"
#include "com_collision.h"
#include "com_heap/com_heap.h"
#include "com_assets.h"

#include "com_types.cpp"
#include "com_maths.cpp"
#include "com_transform.cpp"
#include "com_memory_utils.cpp"
#include "com_render_types.cpp"
#include "com_collision.cpp"
#include "com_heap/com_heap.cpp"
#include "com_assets.cpp"
